name: Publish Github pages

on:
  push:
    branches: [ web ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build IMEs
      run: for f in *.w2k; do python3 grin.py $f; done

    - uses: rayluo/github-pages-overwriter@v1

